# Usa la imagen oficial de Node.js
FROM node:20

# Instalar Dockerize
RUN apt-get update && apt-get install -y wget
RUN wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz \
    && tar -C /usr/local/bin -xzf dockerize-linux-amd64-v0.6.1.tar.gz \
    && rm dockerize-linux-amd64-v0.6.1.tar.gz

# Crea y establece el directorio de trabajo dentro del contenedor
WORKDIR /home/ytoledo

# Copia package.json e instala dependencias
COPY package*.json ./
RUN npm install

# Copia el código fuente de la aplicación
COPY . .

# Exponer el puerto en el que la aplicación escucha
EXPOSE 5555

# Comando para iniciar la aplicación
CMD ["dockerize", "-wait", "tcp://mysql:3306", "-timeout", "20s", "npm", "start"]
