-- MySQL Script generated by MySQL Workbench
-- 12/23/20 13:53:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema y-toledo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `y-toledo` ;

-- -----------------------------------------------------
-- Schema y-toledo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `y-toledo` DEFAULT CHARACTER SET utf8 ;
USE `y-toledo` ;

-- -----------------------------------------------------
-- Table `y-toledo`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `y-toledo`.`roles` ;

CREATE TABLE IF NOT EXISTS `y-toledo`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `y-toledo`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `y-toledo`.`users` ;

CREATE TABLE IF NOT EXISTS `y-toledo`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_id` INT(11) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(100) NULL,
  `email` VARCHAR(100) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `member_num` INT(11) NULL DEFAULT 0,
  `password` VARCHAR(100) NOT NULL,
  `active` TINYINT(4) NULL DEFAULT '1',  
  `attempts` TINYINT(1) NULL DEFAULT 0,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `user_UNIQUE` (`username` ASC),
  INDEX `fk_users_roles_idx` (`role_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`role_id`)
    REFERENCES `y-toledo`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `y-toledo`.`permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `y-toledo`.`permissions` ;

CREATE TABLE IF NOT EXISTS `y-toledo`.`permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `detail` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `y-toledo`.`role_has_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `y-toledo`.`role_has_permission` ;

CREATE TABLE IF NOT EXISTS `y-toledo`.`role_has_permission` (
  `permissions_id` INT(11) NOT NULL,
  `roles_id` INT(11) NOT NULL,
  `reading` TINYINT(1) NULL DEFAULT 0,
  `writing` TINYINT(1) NULL DEFAULT 0,
  INDEX `fk_role_has_permission_permissions1_idx` (`permissions_id` ASC),
  INDEX `fk_role_has_permission_roles1_idx` (`roles_id` ASC),
  CONSTRAINT `fk_role_has_permission_permissions1`
    FOREIGN KEY (`permissions_id`)
    REFERENCES `y-toledo`.`permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_permission_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `y-toledo`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Tabla de rutas
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `y-toledo`.`routes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `start_point` VARCHAR(100) NOT NULL,
  `description` TEXT,
  `distance_km` DECIMAL(5,2) NOT NULL,
  `elevation_gain` INT(11) NOT NULL,
  `max_height` INT(11) NOT NULL,
  `min_height` INT(11) NOT NULL,
  `estimated_duration_hours` INT(2) NOT NULL,
  `estimated_duration_minutes` INT(2) NOT NULL,
  `type` TINYINT(1) NOT NULL,
  `difficulty` VARCHAR(50) NOT NULL,
  `sign_up_link` VARCHAR(255),
  `wikiloc_link` VARCHAR(255),
  `wikiloc_map_link` VARCHAR(255),
  `user_id` INT(11) NULL,
  `file_track` VARCHAR(255) DEFAULT '' COMMENT 'Unique identifier for attached file',
  `filename_track` VARCHAR(255) DEFAULT '' COMMENT 'Original filename with extension for download',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_routes_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_routes_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `y-toledo`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

-- -----------------------------------------------------
-- Data for table `y-toledo`.`roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `y-toledo`;
INSERT INTO `y-toledo`.`roles` (`id`, `name`) VALUES (DEFAULT, 'Administrador');
INSERT INTO `y-toledo`.`roles` (`id`, `name`) VALUES (DEFAULT, 'Usuario');
INSERT INTO `y-toledo`.`roles` (`id`, `name`) VALUES (DEFAULT, 'Invitado');

COMMIT;


-- -----------------------------------------------------
-- Data for table `y-toledo`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `y-toledo`;
INSERT INTO `y-toledo`.`users` (`id`, `name`, `lastname`, `email`, `username`, `password`, `active`, `role_id`) VALUES (DEFAULT, 'Administrador', '', 'jmddesarrollo@gmail.com', 'admin', '$2b$10$1WuyQJGknupSkv6SzRloK.EwvXsd3AHprSj5P39zq4PXk1u5jtAty', 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `y-toledo`.`permissions`
-- -----------------------------------------------------
START TRANSACTION;
USE `y-toledo`;
INSERT INTO `y-toledo`.`permissions` (`id`, `name`, `detail`) VALUES (DEFAULT, 'permissions_manager', 'Gestión de permisos');
INSERT INTO `y-toledo`.`permissions` (`id`, `name`, `detail`) VALUES (DEFAULT, 'users_manager', 'Gestión de usuarios');
INSERT INTO `y-toledo`.`permissions` (`id`, `name`, `detail`) VALUES (DEFAULT, 'files_manager', 'Gestión de archivos');

COMMIT;


-- -----------------------------------------------------
-- Data for table `y-toledo`.`role_has_permission`
-- -----------------------------------------------------
START TRANSACTION;
USE `y-toledo`;
INSERT INTO `y-toledo`.`role_has_permission` (`permissions_id`, `roles_id`, `reading`, `writing`) VALUES ('1', '1', '1', '1');
INSERT INTO `y-toledo`.`role_has_permission` (`permissions_id`, `roles_id`, `reading`, `writing`) VALUES ('2', '1', '1', '1');
INSERT INTO `y-toledo`.`role_has_permission` (`permissions_id`, `roles_id`, `reading`, `writing`) VALUES ('3', '1', '1', '1');

COMMIT;
